import type { Tarjeta, CompraMSI, Transaccion, Inversion, GastoFuturoFijo } from '../types';

export const INITIAL_TARJETAS: Tarjeta[] = [
  {
    id: 'tdc-nu-01',
    user_id: 'demo-user',
    nombre: 'TDC Nu Morada',
    limite_credito: 35000,
    saldo_actual: 5450,
    dia_corte: 12,
    dia_limite_pago: 22,
    color_hex: '#820AD1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tdc-banorte-02',
    user_id: 'demo-user',
    nombre: 'TDC Banorte Oro',
    limite_credito: 50000,
    saldo_actual: 11800,
    dia_corte: 25,
    dia_limite_pago: 15,
    color_hex: '#EB0029',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_MSI: CompraMSI[] = [
  {
    id: 'msi-01',
    user_id: 'demo-user',
    tarjeta_id: 'tdc-nu-01',
    concepto: 'MacBook Air M2 Trabajo',
    monto_total: 18000,
    plazo_meses: 12,
    mensualidades_pagadas: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: 'msi-02',
    user_id: 'demo-user',
    tarjeta_id: 'tdc-banorte-02',
    concepto: 'Refrigerador Inverter Samsung',
    monto_total: 12600,
    plazo_meses: 6,
    mensualidades_pagadas: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'msi-03',
    user_id: 'demo-user',
    tarjeta_id: 'tdc-nu-01',
    concepto: 'Llantas Michelin Auto',
    monto_total: 6400,
    plazo_meses: 4,
    mensualidades_pagadas: 1,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_TRANSACCIONES: Transaccion[] = [
  {
    id: 'tx-01',
    user_id: 'demo-user',
    concepto: 'Nómina Quincenal',
    monto: 24500,
    tipo: 'ingreso',
    categoria: 'Sueldo',
    metodo_pago: 'efectivo_debito',
    tarjeta_id: null,
    fecha: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'tx-02',
    user_id: 'demo-user',
    concepto: 'Supermercado Despensa Familiar',
    monto: 2650,
    tipo: 'gasto',
    categoria: 'Comida',
    metodo_pago: 'efectivo_debito',
    tarjeta_id: null,
    fecha: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'tx-03',
    user_id: 'demo-user',
    concepto: 'Cena Restaurante Italiana',
    monto: 890,
    tipo: 'gasto',
    categoria: 'Restaurantes',
    metodo_pago: 'tarjeta_credito',
    tarjeta_id: 'tdc-nu-01',
    fecha: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'tx-04',
    user_id: 'demo-user',
    concepto: 'Gasolina Shell V-Power',
    monto: 750,
    tipo: 'gasto',
    categoria: 'Transporte',
    metodo_pago: 'tarjeta_credito',
    tarjeta_id: 'tdc-banorte-02',
    fecha: new Date().toISOString().split('T')[0],
  },
  {
    id: 'tx-05',
    user_id: 'demo-user',
    concepto: 'Abono para no generar intereses Banorte',
    monto: 3500,
    tipo: 'pago_tdc',
    categoria: 'Pago TDC',
    metodo_pago: 'efectivo_debito',
    tarjeta_id: 'tdc-banorte-02',
    fecha: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
  {
    id: 'tx-06',
    user_id: 'demo-user',
    concepto: 'Aportación de Ahorro a Cetes',
    monto: 3000,
    tipo: 'inversion',
    categoria: 'Inversión',
    metodo_pago: 'efectivo_debito',
    tarjeta_id: null,
    fecha: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  },
];

export const INITIAL_INVERSIONES: Inversion[] = [
  {
    id: 'inv-01',
    user_id: 'demo-user',
    institucion: 'Cetesdirecto (Bonddia / Cetes 28d)',
    saldo: 45000,
    rendimiento_anual_estimado: 11.25,
    created_at: new Date().toISOString(),
  },
  {
    id: 'inv-02',
    user_id: 'demo-user',
    institucion: 'Nu Cuenta (Cajita 24/7)',
    saldo: 26800,
    rendimiento_anual_estimado: 13.50,
    created_at: new Date().toISOString(),
  },
  {
    id: 'inv-03',
    user_id: 'demo-user',
    institucion: 'Mercado Pago (Fondo Dinámico)',
    saldo: 12500,
    rendimiento_anual_estimado: 10.40,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_GASTOS_FIJOS: GastoFuturoFijo[] = [
  {
    id: 'gf-01',
    user_id: 'demo-user',
    concepto: 'Renta Departamento',
    monto: 8500,
    dia_mes: 1,
    categoria: 'Vivienda',
    pagado_este_mes: true,
  },
  {
    id: 'gf-02',
    user_id: 'demo-user',
    concepto: 'Internet Fibra Óptica Telmex',
    monto: 649,
    dia_mes: 18,
    categoria: 'Servicios',
    pagado_este_mes: false,
  },
  {
    id: 'gf-03',
    user_id: 'demo-user',
    concepto: 'Recibo Luz CFE',
    monto: 530,
    dia_mes: 24,
    categoria: 'Servicios',
    pagado_este_mes: false,
  },
  {
    id: 'gf-04',
    user_id: 'demo-user',
    concepto: 'Gimnasio Smart Fit',
    monto: 599,
    dia_mes: 28,
    categoria: 'Salud',
    pagado_este_mes: false,
  },
];
